version: "3.3"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    stdin_open: true # docker run -i
    tty: true
    entrypoint: /bin/bash
    volumes:
      - ".:/app"
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - db
  db:
    image: mariadb/server:10.3
    ports:
      - "3306:3306"
    volumes:
      - "./localdb:/var/lib/mysql/"
      - "./dbconf:/etc/mysql/conf.d"
    env_file: .env.dev
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
