version: "3.3"
services:
  app:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_HOST
      - PORT
      - DB_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - ADMIN_PASSWORD

    ports:
      - "3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8080:8080"
